version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-mail
    environment:
      POSTGRES_DB: raptrak
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
