import { MigrationInterface, QueryRunner } from "typeorm";

export class UserIdUUID1719934777985 implements MigrationInterface {
    name = 'UserIdUUID1719934777985'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "victory" DROP CONSTRAINT "FK_5042360cb30167f05bb879e2b90"`);
        await queryRunner.query(`ALTER TABLE "victory" DROP COLUMN "winnerId"`);
        await queryRunner.query(`ALTER TABLE "victory" ADD "winnerId" uuid`);
        await queryRunner.query(`ALTER TABLE "venue" DROP CONSTRAINT "FK_ac21b68820c15d2fa90871c7eb2"`);
        await queryRunner.query(`ALTER TABLE "venue" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "venue" ADD "createdById" uuid`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_5a32ea481d14333cc36c38ebfd4"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_e8fb739f08d47955a39850fac23"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "FK_3ce91c19798a3979385eaac5645"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "FK_a324e45161ac4a14dc78f071bb2"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "FK_aeecd03524a8c0f8671b301193c"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "FK_16b4d4ff6b3ce83fdf523f6a91f"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TYPE "public"."user_types_enum" RENAME TO "user_types_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_types_enum" AS ENUM('venue_admin', 'common_user', 'rapper', 'beatmaker', 'host')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" TYPE "public"."user_types_enum"[] USING "types"::"text"::"public"."user_types_enum"[]`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" SET DEFAULT '{common_user}'`);
        await queryRunner.query(`DROP TYPE "public"."user_types_enum_old"`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "like" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "image" DROP COLUMN "uploadedById"`);
        await queryRunner.query(`ALTER TABLE "image" ADD "uploadedById" uuid`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "PK_1e594e77c9aeb532f0d0baff2d5"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "PK_824ef4d9a98a3102f53d394e632" PRIMARY KEY ("rapBattlesId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeecd03524a8c0f8671b301193"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "PK_824ef4d9a98a3102f53d394e632"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "PK_1e594e77c9aeb532f0d0baff2d5" PRIMARY KEY ("rapBattlesId", "userId")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "PK_957bcb5ce16f91e0d98c6153de3"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "PK_8fac672255cf83928b7f513b422" PRIMARY KEY ("rapBattlesId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b4d4ff6b3ce83fdf523f6a91"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "PK_8fac672255cf83928b7f513b422"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "PK_957bcb5ce16f91e0d98c6153de3" PRIMARY KEY ("rapBattlesId", "userId")`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "PK_d04dccc0bde447f29c8d46d0ecc"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "PK_90dbc92364b2e33e5afe1f7f789" PRIMARY KEY ("venueId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce91c19798a3979385eaac564"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "PK_90dbc92364b2e33e5afe1f7f789"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "PK_d04dccc0bde447f29c8d46d0ecc" PRIMARY KEY ("venueId", "userId")`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "PK_2a371531e25086bc7ac3fe770bf"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "PK_14f1105f4f42f38bc15128f37be" PRIMARY KEY ("trackId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a324e45161ac4a14dc78f071bb"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "PK_14f1105f4f42f38bc15128f37be"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "PK_2a371531e25086bc7ac3fe770bf" PRIMARY KEY ("trackId", "userId")`);
        await queryRunner.query(`CREATE INDEX "IDX_aeecd03524a8c0f8671b301193" ON "rap_battles_participants_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16b4d4ff6b3ce83fdf523f6a91" ON "rap_battles_hosts_user" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ce91c19798a3979385eaac564" ON "user_owned_venues_venue" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a324e45161ac4a14dc78f071bb" ON "user_tracks_track" ("userId") `);
        await queryRunner.query(`ALTER TABLE "victory" ADD CONSTRAINT "FK_5042360cb30167f05bb879e2b90" FOREIGN KEY ("winnerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "venue" ADD CONSTRAINT "FK_ac21b68820c15d2fa90871c7eb2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_e8fb739f08d47955a39850fac23" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_5a32ea481d14333cc36c38ebfd4" FOREIGN KEY ("uploadedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "FK_aeecd03524a8c0f8671b301193c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "FK_16b4d4ff6b3ce83fdf523f6a91f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "FK_3ce91c19798a3979385eaac5645" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "FK_a324e45161ac4a14dc78f071bb2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "FK_a324e45161ac4a14dc78f071bb2"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "FK_3ce91c19798a3979385eaac5645"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "FK_16b4d4ff6b3ce83fdf523f6a91f"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "FK_aeecd03524a8c0f8671b301193c"`);
        await queryRunner.query(`ALTER TABLE "image" DROP CONSTRAINT "FK_5a32ea481d14333cc36c38ebfd4"`);
        await queryRunner.query(`ALTER TABLE "like" DROP CONSTRAINT "FK_e8fb739f08d47955a39850fac23"`);
        await queryRunner.query(`ALTER TABLE "venue" DROP CONSTRAINT "FK_ac21b68820c15d2fa90871c7eb2"`);
        await queryRunner.query(`ALTER TABLE "victory" DROP CONSTRAINT "FK_5042360cb30167f05bb879e2b90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a324e45161ac4a14dc78f071bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce91c19798a3979385eaac564"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16b4d4ff6b3ce83fdf523f6a91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeecd03524a8c0f8671b301193"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "PK_2a371531e25086bc7ac3fe770bf"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "PK_14f1105f4f42f38bc15128f37be" PRIMARY KEY ("trackId")`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_a324e45161ac4a14dc78f071bb" ON "user_tracks_track" ("userId") `);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" DROP CONSTRAINT "PK_14f1105f4f42f38bc15128f37be"`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "PK_2a371531e25086bc7ac3fe770bf" PRIMARY KEY ("userId", "trackId")`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "PK_d04dccc0bde447f29c8d46d0ecc"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "PK_90dbc92364b2e33e5afe1f7f789" PRIMARY KEY ("venueId")`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_3ce91c19798a3979385eaac564" ON "user_owned_venues_venue" ("userId") `);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" DROP CONSTRAINT "PK_90dbc92364b2e33e5afe1f7f789"`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "PK_d04dccc0bde447f29c8d46d0ecc" PRIMARY KEY ("userId", "venueId")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "PK_957bcb5ce16f91e0d98c6153de3"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "PK_8fac672255cf83928b7f513b422" PRIMARY KEY ("rapBattlesId")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_16b4d4ff6b3ce83fdf523f6a91" ON "rap_battles_hosts_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" DROP CONSTRAINT "PK_8fac672255cf83928b7f513b422"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "PK_957bcb5ce16f91e0d98c6153de3" PRIMARY KEY ("rapBattlesId", "userId")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "PK_1e594e77c9aeb532f0d0baff2d5"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "PK_824ef4d9a98a3102f53d394e632" PRIMARY KEY ("rapBattlesId")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_aeecd03524a8c0f8671b301193" ON "rap_battles_participants_user" ("userId") `);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" DROP CONSTRAINT "PK_824ef4d9a98a3102f53d394e632"`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "PK_1e594e77c9aeb532f0d0baff2d5" PRIMARY KEY ("rapBattlesId", "userId")`);
        await queryRunner.query(`ALTER TABLE "image" DROP COLUMN "uploadedById"`);
        await queryRunner.query(`ALTER TABLE "image" ADD "uploadedById" integer`);
        await queryRunner.query(`ALTER TABLE "like" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "like" ADD "userId" integer`);
        await queryRunner.query(`CREATE TYPE "public"."user_types_enum_old" AS ENUM('venue_admin', 'common_user', 'rapper', 'beatmaker')`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" TYPE "public"."user_types_enum_old"[] USING "types"::"text"::"public"."user_types_enum_old"[]`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "types" SET DEFAULT '{common_user}'`);
        await queryRunner.query(`DROP TYPE "public"."user_types_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_types_enum_old" RENAME TO "user_types_enum"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rap_battles_hosts_user" ADD CONSTRAINT "FK_16b4d4ff6b3ce83fdf523f6a91f" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rap_battles_participants_user" ADD CONSTRAINT "FK_aeecd03524a8c0f8671b301193c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_tracks_track" ADD CONSTRAINT "FK_a324e45161ac4a14dc78f071bb2" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_owned_venues_venue" ADD CONSTRAINT "FK_3ce91c19798a3979385eaac5645" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "like" ADD CONSTRAINT "FK_e8fb739f08d47955a39850fac23" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image" ADD CONSTRAINT "FK_5a32ea481d14333cc36c38ebfd4" FOREIGN KEY ("uploadedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "venue" DROP COLUMN "createdById"`);
        await queryRunner.query(`ALTER TABLE "venue" ADD "createdById" integer`);
        await queryRunner.query(`ALTER TABLE "venue" ADD CONSTRAINT "FK_ac21b68820c15d2fa90871c7eb2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "victory" DROP COLUMN "winnerId"`);
        await queryRunner.query(`ALTER TABLE "victory" ADD "winnerId" integer`);
        await queryRunner.query(`ALTER TABLE "victory" ADD CONSTRAINT "FK_5042360cb30167f05bb879e2b90" FOREIGN KEY ("winnerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
